services:
  random-decision-maker:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - RESULTS_FILE=/results/Decisions.csv
      - API_HOST=http://localhost:8080
      - CONF_PARAM=EncodingThreadCount
      - RANGE_MIN=1
      - RANGE_MAX=16
      - SLEEP_INTERVAL=180 # 5 minutes
    volumes:
      - ./results:/results